Clean up

diff --git a/lib/glassfish-5.0/glassfish5/mq/bin/imqbrokerd b/lib/glassfish-5.0/glassfish5/mq/bin/imqbrokerd
--- a/lib/glassfish-5.0/glassfish5/mq/bin/imqbrokerd
+++ b/lib/glassfish-5.0/glassfish5/mq/bin/imqbrokerd
@@ -52,47 +52,47 @@
 # Terminate the broker
 #
 shutdown_broker() {
-    # The broker's shutdown hooks will make sure it exits cleanly
-    if [ -n "$_javapid" ]; then
-        kill -TERM $_javapid
-    fi
+  # The broker's shutdown hooks will make sure it exits cleanly
+  if [ -n "$_javapid" ]; then
+    kill -TERM $_javapid
+  fi
 }
 
-_bin_home=`/usr/bin/dirname $0`
+_bin_home=$(/usr/bin/dirname $0)
 _init_file="imqinit"
 
 # Source initialization file. This intitializes the imq_* variables
 if [ -f $_bin_home/../share/lib/imq/$_init_file ]; then
-    # bundled location
-    . $_bin_home/../share/lib/imq/$_init_file
+  # bundled location
+  . $_bin_home/../share/lib/imq/$_init_file
 elif [ -f $_bin_home/../lib/$_init_file ]; then
-    # unbundled location
-    . $_bin_home/../lib/$_init_file
+  # unbundled location
+  . $_bin_home/../lib/$_init_file
 elif [ -f $_bin_home/../private/share/lib/$_init_file ]; then
-    # Linux "standard" location
-    . $_bin_home/../private/share/lib/$_init_file
+  # Linux "standard" location
+  . $_bin_home/../private/share/lib/$_init_file
 #####hpux-dev#####
 elif [ -f $_bin_home/../private/share/lib/$_init_file ]; then
-    # HP-UX "standard" location
-    . $_bin_home/../private/share/lib/$_init_file
+  # HP-UX "standard" location
+  . $_bin_home/../private/share/lib/$_init_file
 else
-    echo "Error: Could not find required Message Queue initialization file '$_init_file'"
-    exit 1
+  echo "Error: Could not find required Message Queue initialization file '$_init_file'"
+  exit 1
 fi
 
 # create $imq_varhome/instances directory if it does not exist
 # and set permissions to 1777
 # (this operation used to be done by installer)
 if [ ! -d "$imq_varhome/instances" ]; then
-   mkdir -p $imq_varhome/instances
-   chmod 1777 $imq_varhome/instances
+  mkdir -p $imq_varhome/instances
+  chmod 1777 $imq_varhome/instances
 fi
 
 # Specify default arguments to the JVM here
 if [ "$imq_os" = "Linux" ]; then
-_def_jvm_args="-Xms192m -Xmx192m -Xss256k"
+  _def_jvm_args="-Xms192m -Xmx192m -Xss256k"
 else
-_def_jvm_args="-Xms192m -Xmx192m -Xss192k"
+  _def_jvm_args="-Xms192m -Xmx192m -Xss192k"
 fi
 # We will add vendor-specific JVM flags below
 
@@ -106,40 +106,40 @@ _classpath=$imq_sharelibimq_home/imqbroker.jar:$imq_sharelibimq_home/imqutil.jar
 #
 jesmf_jars=""
 if [ $imq_os = "SunOS" ]; then
-    jesmf_jars=/opt/SUNWjdmk/5.1/lib/jdmkrt.jar:/opt/SUNWmfwk/lib/mfwk_instrum_tk.jar
+  jesmf_jars=/opt/SUNWjdmk/5.1/lib/jdmkrt.jar:/opt/SUNWmfwk/lib/mfwk_instrum_tk.jar
 elif [ "$imq_os" = "Linux" ]; then
-    jesmf_jars=/opt/sun/mfwk/share/lib/jdmkrt.jar:/opt/sun/mfwk/share/lib/mfwk_instrum_tk.jar
+  jesmf_jars=/opt/sun/mfwk/share/lib/jdmkrt.jar:/opt/sun/mfwk/share/lib/mfwk_instrum_tk.jar
 else
-    jesmf_jars=/opt/sun/mfwk/share/lib/jdmkrt.jar:/opt/sun/mfwk/share/lib/mfwk_instrum_tk.jar
+  jesmf_jars=/opt/sun/mfwk/share/lib/jdmkrt.jar:/opt/sun/mfwk/share/lib/mfwk_instrum_tk.jar
 fi
 
 _classpath=$_classpath:$jesmf_jars
 
 # Default external JARs
 if [ ! -z "$imq_ext_jars" ]; then
-    _classpath=$_classpath:$imq_ext_jars
+  _classpath=$_classpath:$imq_ext_jars
 fi
 
 # Additional classes possibly needed for JDBC provider, etc.
 _classpath=$_classpath:$imq_sharelibimq_home/ext
 # Put all jar files in $IMQ_SHARELIB_HOME/ext in our CLASSPATH
 for _file in $imq_sharelibimq_home/ext/*.jar $imq_sharelibimq_home/ext/*.zip; do
-    if [ -r "$_file" ]; then
-        _classpath=$_classpath:$_file
-    fi
+  if [ -r "$_file" ]; then
+    _classpath=$_classpath:$_file
+  fi
 done
 
 # On Linux they may be here (as of 3.6)
 _classpath=$_classpath:$imq_sharelib_home/ext
 # Put all jar files in $IMQ_SHARELIB_HOME/ext in our CLASSPATH
 for _file in $imq_sharelib_home/ext/*.jar $imq_sharelib_home/ext/*.zip; do
-    if [ -r "$_file" ]; then
-        _classpath=$_classpath:$_file
-    fi
+  if [ -r "$_file" ]; then
+    _classpath=$_classpath:$_file
+  fi
 done
 
 # Broker's main class
-_mainclass=com.sun.messaging.jmq.jmsserver.Broker;
+_mainclass=com.sun.messaging.jmq.jmsserver.Broker
 
 _background=""
 _verbose=""
@@ -150,69 +150,89 @@ _managed=""
 # Parse command line arguments
 while [ $# != 0 ]; do
   case "$1" in
-    -bgnd) _background="true"; _args="$_args $1"; shift ;;
-    -autorestart) _autorestart="true"; shift ;;
-    -managed) _managed="true"; shift ;;
-    -verbose) _verbose="true"; shift ;;
-    -clientvm) _forceclientvm="true"; shift ;;
-    -vmargs) shift; _jvm_args="$1 $_jvm_args"; shift ;;
-    *)  _args="$_args $1"; shift  ;;
+  -bgnd)
+    _background="true"
+    _args="$_args $1"
+    shift
+    ;;
+  -autorestart)
+    _autorestart="true"
+    shift
+    ;;
+  -managed)
+    _managed="true"
+    shift
+    ;;
+  -verbose)
+    _verbose="true"
+    shift
+    ;;
+  -clientvm)
+    _forceclientvm="true"
+    shift
+    ;;
+  -vmargs)
+    shift
+    _jvm_args="$1 $_jvm_args"
+    shift
+    ;;
+  *)
+    _args="$_args $1"
+    shift
+    ;;
   esac
 done
 
 # Check to see if we can run with the -server flag
 #
 # If user is forcing client vm then don't use server VM
-if [ -n "$_forceclientvm" ] ; then
-    imq_servervm=""
+if [ -n "$_forceclientvm" ]; then
+  imq_servervm=""
 fi
 
-
 # If the script is killed make sure we shutdown the Broker's Java process
-trap "shutdown_broker" TERM INT QUIT 
-
+trap "shutdown_broker" TERM INT QUIT
 
 #####hpux-dev#####
-PLATFORM=`uname`
+PLATFORM=$(uname)
 
 # Set LD_LIBRARY_PATH to locate libimq
 # If the -d64 option was passed to the JVM and we are on Solaris
 # then adjust the library path to find the 64 bit version of libimqutil first.
 # Else use the 32bit version
-_d64=`echo $_jvm_args $_def_jvm_args | grep "\-d64"`
+_d64=$(echo $_jvm_args $_def_jvm_args | grep "\-d64")
 if [ "$_d64" ]; then
   if [ $imq_os = "SunOS" ]; then
     if [ "$imq_proc" = "sparc" ]; then
-        LD_LIBRARY_PATH=$imq_libhome/sparcv9:$LD_LIBRARY_PATH
-        export LD_LIBRARY_PATH
+      LD_LIBRARY_PATH=$imq_libhome/sparcv9:$LD_LIBRARY_PATH
+      export LD_LIBRARY_PATH
     elif [ "$imq_proc" = "i386" ]; then
-        LD_LIBRARY_PATH=$imq_libhome/amd64:$LD_LIBRARY_PATH
-        export LD_LIBRARY_PATH
+      LD_LIBRARY_PATH=$imq_libhome/amd64:$LD_LIBRARY_PATH
+      export LD_LIBRARY_PATH
     fi
   fi
   # For the 64bit JVM we need a larger stack size
   _def_jvm_args="$_def_jvm_args -Xss256k"
 else
-    if [ "$PLATFORM" = HP-UX ] ; then
+  if [ "$PLATFORM" = HP-UX ]; then
     SHLIB_PATH=$SHLIB_PATH:$imq_libhome
     export SHLIB_PATH
     _def_jvm_args="$_def_jvm_args -Xss256k"
-    else
+  else
     LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$imq_libhome
     export LD_LIBRARY_PATH
-    fi
+  fi
 fi
 
 # Add vendor-specific JVM flags
-$imq_javahome/bin/java -version 2>&1 | grep JRockit > /dev/null
+$imq_javahome/bin/java -version 2>&1 | grep JRockit >/dev/null
 if [ $? -eq 0 ]; then
-   # Add JRockit-specific JVM flags
-   _jvm_args="$_jvm_args -XgcPrio:deterministic"
+  # Add JRockit-specific JVM flags
+  _jvm_args="$_jvm_args -XgcPrio:deterministic"
 else
-   # Add Sun-specific JVM flags
-   _jvm_args="$_jvm_args -XX:MaxGCPauseMillis=5000"
+  # Add Sun-specific JVM flags
+  _jvm_args="$_jvm_args -XX:MaxGCPauseMillis=5000"
 fi
-
 
 # Setup arguments to the JVM
 _jvm_args="$_def_jvm_args $_jvm_args -Dimq.home=$imq_home -Dimq.varhome=$imq_varhome -Dimq.etchome=$imq_etchome -Dimq.libhome=$imq_sharelibimq_home"
@@ -220,15 +240,14 @@ _jvm_args="$_def_jvm_args $_jvm_args -Dimq.home=$imq_home -Dimq.varhome=$imq_var
 # The command we use to run the broker
 _brokercmd="$imq_javahome/bin/java $imq_servervm -cp $_classpath $_jvm_args $_mainclass $_args"
 
-
 if [ ! -z "$_verbose" ]; then
-    if [ "$PLATFORM" = HP-UX ] ; then
+  if [ "$PLATFORM" = HP-UX ]; then
     echo " SHLIB_PATH  : $SHLIB_PATH"
-    else
+  else
     echo "  LD_LIBRARY_PATH  : $LD_LIBRARY_PATH"
-    fi
-    echo "Command:"
-    echo "    $_brokercmd"
+  fi
+  echo "Command:"
+  echo "    $_brokercmd"
 fi
 
 # Set umask so any files created by broker are only accessible
@@ -240,47 +259,47 @@ umask 077
 # then 0, 1, 129 (SIGHUP), 130 (SIGINT), or 143 (SIGTERM)) then restart.
 _restart=true
 while [ $_restart ]; do
-    _javapid=""
-    if [ -n "$_background" ]; then
-        $_brokercmd &
-        # If we are running in the background use wait to wait for child
-        _javapid=$!
-        wait $_javapid
-        _status=$?
-    else
-        $_brokercmd
-        _status=$?
-    fi
+  _javapid=""
+  if [ -n "$_background" ]; then
+    $_brokercmd &
+    # If we are running in the background use wait to wait for child
+    _javapid=$!
+    wait $_javapid
+    _status=$?
+  else
+    $_brokercmd
+    _status=$?
+  fi
 
-    if [ $_status -eq 255 ]; then
-        # 255 means restart
-        if [ ! -z "$_managed" ]; then
-           # Managed by Glassfish. Don't restart here, let Glassfish do it
-           logger -t imqbrokerd -p daemon.notice imqbrokerd completed with status 255 - letting Glassfish restart
-           _restart=
-        else
-           # Managed by this script. Restart broker
-           sleep 0
-        fi
-	# We pause to avoid pegging system if we get here accidentally
-	sleep 1
-    elif [ $_status -eq 0 -o $_status -eq 1 -o $_status -eq 129 -o $_status -eq 130 -o $_status -eq 143 ]; then
-        # "Normal" termination. Don't restart
-        _restart=
-    elif [ ! -z "$_autorestart" ]; then
-        # Abnormal termination and autorestart specified 
-        if [ ! -z "$_managed" ]; then
-           # Managed by Glassfish. Ignore _autorestart 
-           sleep 0
-        else
-           # Managed by this script. Restart broker
-        logger -t imqbrokerd -p daemon.notice Message Queue broker terminated abnormally -- restarting.
-        sleep 2
-        fi
+  if [ $_status -eq 255 ]; then
+    # 255 means restart
+    if [ ! -z "$_managed" ]; then
+      # Managed by Glassfish. Don't restart here, let Glassfish do it
+      logger -t imqbrokerd -p daemon.notice imqbrokerd completed with status 255 - letting Glassfish restart
+      _restart=
     else
-        # Abnormal termination but autorestart not specified - simply exit
-	_restart=
+      # Managed by this script. Restart broker
+      sleep 0
     fi
+    # We pause to avoid pegging system if we get here accidentally
+    sleep 1
+  elif [ $_status -eq 0 -o $_status -eq 1 -o $_status -eq 129 -o $_status -eq 130 -o $_status -eq 143 ]; then
+    # "Normal" termination. Don't restart
+    _restart=
+  elif [ ! -z "$_autorestart" ]; then
+    # Abnormal termination and autorestart specified
+    if [ ! -z "$_managed" ]; then
+      # Managed by Glassfish. Ignore _autorestart
+      sleep 0
+    else
+      # Managed by this script. Restart broker
+      logger -t imqbrokerd -p daemon.notice Message Queue broker terminated abnormally -- restarting.
+      sleep 2
+    fi
+  else
+    # Abnormal termination but autorestart not specified - simply exit
+    _restart=
+  fi
 done
 
 exit $_status
diff --git a/lib/glassfish-5.0/glassfish5/mq/bin/imqdbmgr b/lib/glassfish-5.0/glassfish5/mq/bin/imqdbmgr
--- a/lib/glassfish-5.0/glassfish5/mq/bin/imqdbmgr
+++ b/lib/glassfish-5.0/glassfish5/mq/bin/imqdbmgr
@@ -49,35 +49,45 @@
 # Specify additional arguments to the JVM here
 _def_jvm_args="-Xmx128m"
 
-_bin_home=`/usr/bin/dirname $0`
+_bin_home=$(/usr/bin/dirname $0)
 _init_file="imqinit"
 
 # Source initialization file. This intitializes the imq_* variables
 if [ -f $_bin_home/../share/lib/imq/$_init_file ]; then
-    # bundled location
-    . $_bin_home/../share/lib/imq/$_init_file
+  # bundled location
+  . $_bin_home/../share/lib/imq/$_init_file
 elif [ -f $_bin_home/../lib/$_init_file ]; then
-    # unbundled location
-    . $_bin_home/../lib/$_init_file
+  # unbundled location
+  . $_bin_home/../lib/$_init_file
 elif [ -f $_bin_home/../private/share/lib/$_init_file ]; then
-    # Linux "standard" location
-    . $_bin_home/../private/share/lib/$_init_file
+  # Linux "standard" location
+  . $_bin_home/../private/share/lib/$_init_file
 #####hpux-dev#####
 elif [ -f $_bin_home/../private/share/lib/$_init_file ]; then
-    # HP-UX "standard" location
-    $_bin_home/../private/share/lib/$_init_file
+  # HP-UX "standard" location
+  $_bin_home/../private/share/lib/$_init_file
 else
-    echo "Error: Could not find required Message Queue initialization file '$_init_file'"
-    exit 1
+  echo "Error: Could not find required Message Queue initialization file '$_init_file'"
+  exit 1
 fi
 
 # Parse command line arguments. We eat these so they are not passed to dbmgr
 while [ $# != 0 ]; do
   case "$1" in
-    -verbose) _verbose=true; shift 1;;
-    -javahome) shift 2;;
-    -vmargs) shift; _jvm_args="$1 $_jvm_args"; shift ;;
-    *)  args="$args $1"; shift  ;;
+  -verbose)
+    _verbose=true
+    shift 1
+    ;;
+  -javahome) shift 2 ;;
+  -vmargs)
+    shift
+    _jvm_args="$1 $_jvm_args"
+    shift
+    ;;
+  *)
+    args="$args $1"
+    shift
+    ;;
   esac
 done
 
@@ -86,16 +96,16 @@ _classes=$imq_sharelibimq_home/imqbroker.jar
 
 # Default external JARs
 if [ ! -z "$imq_ext_jars" ]; then
-    _classes=$_classes:$imq_ext_jars
+  _classes=$_classes:$imq_ext_jars
 fi
 
 # Additional classes possibly needed for JDBC provider
 _classes=$_classes:$imq_sharelibimq_home/ext
 # Put all jar and zip files in $imq_varhome/lib in the classpath
 for file in $imq_sharelibimq_home/ext/*.jar $imq_sharelibimq_home/ext/*.zip; do
-    if [ -r "$file" ]; then
-	_classes=$_classes:$file
-    fi
+  if [ -r "$file" ]; then
+    _classes=$_classes:$file
+  fi
 done
 
 #####hpux-dev#####
@@ -103,9 +113,9 @@ done
 _classes=$_classes:$imq_sharelib_home/ext
 # Put all jar files in $IMQ_SHARELIB_HOME/ext in our CLASSPATH
 for _file in $imq_sharelib_home/ext/*.jar $imq_sharelib_home/ext/*.zip; do
-    if [ -r "$_file" ]; then
-        _classes=$_classes:$_file
-    fi
+  if [ -r "$_file" ]; then
+    _classes=$_classes:$_file
+  fi
 done
 
 # imqdbmgr's main class
@@ -116,13 +126,14 @@ jvm_args="$_def_jvm_args $_jvm_args -Dimq.home=$imq_home -Dimq.varhome=$imq_varh
 
 # Needed to locate libimq
 #####hpux-dev#####
-PLATFORM=`uname`
-if [ "$PLATFORM" = HP-UX ] ; then
-SHLIB_PATH=$SHLIB_PATH:$imq_libhome; export SHLIB_PATH
+PLATFORM=$(uname)
+if [ "$PLATFORM" = HP-UX ]; then
+  SHLIB_PATH=$SHLIB_PATH:$imq_libhome
+  export SHLIB_PATH
 else
-LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$imq_libhome; export LD_LIBRARY_PATH
+  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$imq_libhome
+  export LD_LIBRARY_PATH
 fi
 
 # run imqdbmgr
 "$imq_javahome/bin/java" -cp $_classes $jvm_args $_mainclass $args
-
diff --git a/lib/glassfish-5.0/glassfish5/mq/bin/imqobjmgr b/lib/glassfish-5.0/glassfish5/mq/bin/imqobjmgr
--- a/lib/glassfish-5.0/glassfish5/mq/bin/imqobjmgr
+++ b/lib/glassfish-5.0/glassfish5/mq/bin/imqobjmgr
@@ -46,26 +46,26 @@
 # Specify additional arguments to the JVM here
 jvm_args="-Xmx128m"
 
-_bin_home=`/usr/bin/dirname $0`
+_bin_home=$(/usr/bin/dirname $0)
 _init_file="imqinit"
 
 # Source initialization file. This intitializes the imq_* variables
 if [ -f $_bin_home/../share/lib/imq/$_init_file ]; then
-    # bundled location
-    . $_bin_home/../share/lib/imq/$_init_file
+  # bundled location
+  . $_bin_home/../share/lib/imq/$_init_file
 elif [ -f $_bin_home/../lib/$_init_file ]; then
-    # unbundled location
-    . $_bin_home/../lib/$_init_file
+  # unbundled location
+  . $_bin_home/../lib/$_init_file
 elif [ -f $_bin_home/../private/share/lib/$_init_file ]; then
-    # Linux "standard" location
-    . $_bin_home/../private/share/lib/$_init_file
+  # Linux "standard" location
+  . $_bin_home/../private/share/lib/$_init_file
 #####hpux-dev#####
 elif [ -f $_bin_home/../private/share/lib/$_init_file ]; then
-    # HP-UX "standard" location
-    . $_bin_home/../private/share/lib/$_init_file
+  # HP-UX "standard" location
+  . $_bin_home/../private/share/lib/$_init_file
 else
-    echo "Error: Could not find required Message Queue initialization file '$_init_file'"
-    exit 1
+  echo "Error: Could not find required Message Queue initialization file '$_init_file'"
+  exit 1
 fi
 
 jvm_args="$jvm_args -Dimq.home=$imq_home -Dimq.varhome=$imq_varhome"
@@ -74,27 +74,28 @@ jvm_args="$jvm_args -Dimq.home=$imq_home -Dimq.varhome=$imq_varhome"
 # Append CLASSPATH value to _classes if it is set.
 #
 if [ ! -z "$CLASSPATH" ]; then
-    _classes=$imq_sharelibimq_home/imqadmin.jar:$imq_sharelib_home/fscontext.jar:$CLASSPATH
-    CLASSPATH=
-    export CLASSPATH
+  _classes=$imq_sharelibimq_home/imqadmin.jar:$imq_sharelib_home/fscontext.jar:$CLASSPATH
+  CLASSPATH=
+  export CLASSPATH
 else
-    _classes=$imq_sharelibimq_home/imqadmin.jar:$imq_sharelib_home/fscontext.jar
+  _classes=$imq_sharelibimq_home/imqadmin.jar:$imq_sharelib_home/fscontext.jar
 fi
 
 # Default external JARs
 if [ ! -z "$imq_ext_jars" ]; then
-    _classes=$_classes:$imq_ext_jars
+  _classes=$_classes:$imq_ext_jars
 fi
 
 _mainclass=com.sun.messaging.jmq.admin.apps.objmgr.ObjMgr
 
 # Needed to locate libimq
 #####hpux-dev#####
-if [ "$PLATFORM" = HP-UX ] ; then
-SHLIB_PATH=$SHLIB_PATH:$imq_libhome; export SHLIB_PATH
+if [ "$PLATFORM" = HP-UX ]; then
+  SHLIB_PATH=$SHLIB_PATH:$imq_libhome
+  export SHLIB_PATH
 else
-LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$imq_libhome; export LD_LIBRARY_PATH
+  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$imq_libhome
+  export LD_LIBRARY_PATH
 fi
-
 
 "$imq_javahome/bin/java" -cp "$_classes" $jvm_args $_mainclass "$@"
